import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { styled } from '@mui/material/styles';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import * as React from 'react';
import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import {CardActionArea} from '@mui/material';
import Grid from '@mui/material/Grid';
import Paper from '@mui/material/Paper';
import "react-slideshow-image/dist/styles.css";
import Box from '@mui/material/Box';

const theme = createTheme({
  typography: {
    h1:{
      fontSize:300,
      textTransform:"uppercase",
      textAlign:"center",
      fontFamily: 'Dahlia',
      letterSpacing:"20px",
      color:'##0C0A09',
      marginTop:"10rem",
    },
    subtitle1: {
      fontSize: 12,
    },
    body1: {
      fontWeight: 500,
    },
    button: {
      fontStyle: 'italic',
    },
    p:{
      fontFamily: 'Letter Gothic',
   width:"20%",
   textAlign:"left",
    },
  },
});
const images = ["https://marabouparken.se/wp-content/uploads/2013/07/Les-Trois-Amis.jpg", "https://www.enca.com/sites/default/files/afp/2021-10/doc-9PC9DM-%40photo0.jpg", "https://momaa.org/wp-content/uploads/2020/04/Malick-Sidib%C3%A9.jpg","https://momaa.org/wp-content/uploads/2020/04/Untitled-1949-1951-C-Seydou-Ke%C3%AFta.jpg"];
const zoomOutProperties = {
  duration: 100,
  transitionDuration: 50,
  infinite: true,
  indicators: true,
  arrows: true
};

const Slideshow = () => {
  return (
    <div className="slide-container">
      <Zoom {...zoomOutProperties}>
        {images.map((each, index) => (
          <img key={index} style={{ width: "100%" }} src={each} />
        ))}
      </Zoom>
    </div>
  );
};
const Item = styled(Paper)(({ theme }) => ({
  backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
  ...theme.typography.body2,
  padding: theme.spacing(1),
  textAlign: 'center',
  color: theme.palette.text.secondary,
}));
const style = {
  imageContainer: {
      backgroundImage: "red",
  }
};
export default function Home() {
  return (
<div className="wrapper">
<div className="landing-screen">
  </div>  
<div className={styles.container}>
      <Head>
        <title>Maarifa blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <Typography variant="h1">Maarifa</Typography>
      </ThemeProvider>
<div>
<img width="100%" height="100%" src="https://i.guim.co.uk/img/media/0e0714859d891913996c5c7c3b1241d4d616473b/0_0_2493_1661/master/2493.jpg?width=1920&quality=85&auto=format&fit=max&s=c548bb535ef1923f055311822a61176d" />
</div>

<Box m={8} 
        sx={{
          height: '100vh',
          width: "100%",
          display: 'inline-block',
          p: 1,
          mx: 1,
          bgcolor: (theme) =>
            theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',
          border: '1px solid',
          borderColor: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.800' : 'grey.300',
          borderRadius: 2,
          fontSize: '0.875rem',
          fontWeight: '700',
          textAlign: 'center',
          position: 'relative',
        }}
      >
        <Box
        sx={{
          width: '50%',
          p: 1,
          my: 1,
          bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',
          border: '1px solid',
          borderColor: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.800' : 'grey.300',
          borderRadius: 2,
          fontSize: '0.875rem',
          fontWeight: '700',
          textAlign: 'center',
          marginTop:"8rem",
        }}
      >
     <ThemeProvider theme={theme}>
        <Typography  variant="p" className="intro">Maarifa, the swahili word for "knowledge". The significance of that word lies within the purpose of this blog. This blog will serve as a digital space to connect with untold stories of a very faceted continent. Africa. Through publicly available media, Maarifa blog will showcase Africa from its muzzy pre-colonial incpetion, some of continent's most influential figures, the global cultural blueprints it has set, where the continent is today and where we can see Africa going and becoming {
          
        }.   </Typography>
        </ThemeProvider>
      </Box>
      <div style={{ width: '100%', display:"flex", justifyContent:"flex-end",position:"absolute",  gap:25, bottom:0, right:0}}>
        
      <Card 
      class=
      'card' sx={{ maxWidth: 380, boxShadow:0, bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography>
        <CardMedia
          component="img"
          height="220"
          image="https://img.theculturetrip.com/1440x807/smart/wp-content/uploads/2018/09/rexfeatures_7339260c.jpg"
          alt="green iguana"
        />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
            Lizards are a widespread group of squamate reptiles, with over 6,000
            species, ranging across all continents except Antarctica
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
    <Card  sx={{ maxWidth: 380,  boxShadow:0, bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800', }}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Golden Age of Mali Photography
          </Typography>
        <CardMedia
          component="img"
          height="220"
          image="https://momaa.org/wp-content/uploads/2020/04/Untitled-1949-1951-C-Seydou-Ke%C3%AFta.jpg"
          alt="green iguana"
        />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
            Lizards are a widespread group of squamate reptiles, with over 6,000
            species, ranging across all continents except Antarctica
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
        Read more
        </Button>
      </CardActions>
    </Card>
    <Card sx={{ maxWidth: 380,  boxShadow:0, bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800', }}>
      <CardActionArea>
                  <Typography gutterBottom variant="subtitle1" component="div">
     / Mother Africa - Timbuktu
          </Typography>
        <CardMedia
          component="img"
          height="220"
          image="http://inapcache.boston.com/universal/site_graphics/blogs/bigpicture/mali_092112/bp1.jpg"
          alt="green iguana"
        />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
            Lizards are a widespread group of squamate reptiles, with over 6,000
            species, ranging across all continents except Antarctica
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
        Read more 
        </Button>
      </CardActions>
    </Card>
      </div >
      </Box>
      <Box sx={{ flexGrow: 1, height:"100%",  backgroundColor: '#dcd6c8',}}>
      <Grid container sx={{ flexGrow: 1, height:"100vh",  backgroundColor: '#dcd6c8',}}>
        <Grid item xs={6} style={style.paperContainer}  sx={{backgroundColor: '#dcd6c8', display:'flex', justifyContent:'center', alignItems:'center'}} >
        
          <Card sx={{ maxWidth: 350,  boxShadow:0, backgroundColor: '#dcd6c8' }}>
      <CardActionArea>
     
        <CardMedia
          component="img"
          height="350"
      image="https://autograph.org.uk/Content/Images/EditorImages/a%20-%20new%20structure%2Fonline%20image%20galleries%2F2021%2Foctober%2Fbarnor%2FBarnor-EY-stand.jpg"
          alt="green iguana"
        />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Yoga undergraduate Peter Dodoo, a student of Mr Strong #1, Ever Young studio, Accra, c. 1955
          <br />
          James Barnor 
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
     
    </Card>
        </Grid>
        <Grid item xs={6} sx={{backgroundImage:`url(https://i.guim.co.uk/img/media/4ea2d56aa4b5c9a04db58900318f4f1ce40c823c/0_0_3543_3582/master/3543.jpg?width=1010&quality=45&auto=format&fit=max&dpr=2&s=8dc5eb97fefac1b49200de4f192db7ac)`, backgroundPosition:'center', backgroundSize:"cover"}}>
          {
          
        //   <Item> <CardMedia
        //   component="img"
   
        //   // image="https://i.guim.co.uk/img/media/4ea2d56aa4b5c9a04db58900318f4f1ce40c823c/0_0_3543_3582/master/3543.jpg?width=1010&quality=45&auto=format&fit=max&dpr=2&s=8dc5eb97fefac1b49200de4f192db7ac"
        //   alt="green iguana"
     
        // />
        // </Item>
        }
        </Grid>
      </Grid>
    </Box>
    <Box sx={{ flexGrow: 1, height:"100vh",position:"relative"}}>
      <Grid container spacing={2} sx={{paddingTop:10}}>
        <Grid item xs={5}>
          {/* <Item>xs=8</Item> */}
        </Grid>
        <Grid item xs={7} sx={{ display: 'flex', justifyContent:'flex-end', gap:4}}>
      
          <Card 
      class=
      'card' sx={{ maxWidth: 350, boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography>
        <CardMedia
          component="img"
          height="250"
          image="https://live.staticflickr.com/7031/6507232963_e88cd0dfe9_b.jpg"
          alt="green iguana"
        />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
            Lizards are a widespread group of squamate reptiles, with over 6,000
            species, ranging across all continents except Antarctica
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
    <Card 
      class=
      'card' sx={{ maxWidth: 280,  boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography>
        <CardMedia
          component="img"
          height="350"
          image="https://media.gettyimages.com/photos/the-bamangwato-chief-with-his-wife-formerly-ruth-williams-their-in-picture-id613477214?k=20&m=613477214&s=612x612&w=0&h=etwlj8mhBrdOMFoa3FQdQn6mwbMxMV9DVLt1VduBPAs="
          alt="green iguana"
        />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          The Bamangwato chief with his wife, formerly Ruth Williams. Their marriage, in 1948, caused Seretse Khama to be banished from Bechuanaland and deposed as chief. He returned a few years later and, promoting multiracial policies, became prime minister.
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
        
        
        </Grid>
        <Grid item xs={4} sx={{ border:0, boxShadow:0, height:"100%",}}>
          <Item sx={{position:"absolute", bottom:0,  border:0, boxShadow:0, backgroundColor:"transparent",}}>

          <Card 
      class=
      'card' sx={{ maxWidth: 450,  boxShadow:0, border:0, bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      {/* <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography> */}
        <CardMedia
          component="img"
          height="280"
          image="https://media.gettyimages.com/photos/6171960leopoldville-belgian-congo-congo-political-leader-patrice-picture-id515218934?k=20&m=515218934&s=612x612&w=0&h=0iJ-Kuu-QpvQG5IMK97u9nPBmyxNh8adxdlTp0fz5vQ="
          alt="green iguana"
        />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          (Original Caption) 6/17/1960-Leopoldville, Belgian Congo- Congo political leader Patrice Lumumba, shown addressing Parliament, won his first test of strength in Parliament, June 21, and as a result was designated to form a government of the Congo. The Congo gets its independence from Belgium on June 30th.
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
          </Item>
        </Grid>
     
        <Grid item xs={8}>
          {/* <Item>xs=8</Item> */}
        </Grid>
      </Grid>
    </Box>


    <Grid container  xs={{height:"100%", backgroundColor:"red"}}>
  <Grid item xs={6} md={4}>
    <Item>
    <h3>Political</h3>
    </Item>
  </Grid>
  <Grid item xs={6} md={8}>
  
  <Grid container spacing={1}>
  <Grid item xs>
  <Card 
      class=
      'card' sx={{ maxWidth: 300, boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography>
        <CardMedia
          component="img"
          height="220"
          image="https://live.staticflickr.com/7031/6507232963_e88cd0dfe9_b.jpg"
          alt="green iguana"
        />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
            Lizards are a widespread group of squamate reptiles, with over 6,000
            species, ranging across all continents except Antarctica
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>

  </Grid>
  <Grid item xs>
  <Card 
      class=
      'card' sx={{ maxWidth: "100%", boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography>
       <img class="img"
       src="https://lh3.googleusercontent.com/RkyTiCFq4ZUQE2S30s8I9LAgS1EkXqqr9QlmjSy6NXOKBiw1bfqAeRLPWmf-hSCmUOpuBjf5AfhBNkkyjSfr" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          196: Picketer holding Steve Biko's portrait during a demonstration in Oxford Street during The South African Truth and Reconciliation Commission (TRC) hearings in East London. (Photo by Gallo Images/Oryx Media Archive/Getty Images)
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
  </Grid>
  <Grid item xs={6}>

  <Card 
      class=
      'card' sx={{ maxWidth: 330, boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
  / The love story that shocked the world
          </Typography>
        <CardMedia
          component="img"
          height="220"
          image="https://im4.ezgif.com/tmp/ezgif-4-ca215c8566.gif"
          alt="green iguana"
        />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
            Lizards are a widespread group of squamate reptiles, with over 6,000
            species, ranging across all continents except Antarctica
            <br />
            BBC News
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
  </Grid>
</Grid>
<Grid container spacing={4}>
  <Grid item xs>

  </Grid>
  <Grid item xs={3}>
  <Card 
      class=
      'card' sx={{ maxWidth: 300, boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography>
        <CardMedia
          component="img"
          height="220"
          image="https://live.staticflickr.com/7031/6507232963_e88cd0dfe9_b.jpg"
          alt="green iguana"
        />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
            Lizards are a widespread group of squamate reptiles, with over 6,000
            species, ranging across all continents except Antarctica
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
  </Grid>
  <Grid item  xs={4}>
    <Card 
      class=
      'card' sx={{ width: 450, boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
    
          </Typography>
     <img src="https://media.gettyimages.com/photos/picketer-holding-steve-bikos-portrait-during-a-demonstration-in-picture-id107880745?k=20&m=107880745&s=612x612&w=0&h=_IJCQE6GcmAe4MKNWjClH8JfLONTgWMc9Zj8mzLoFes=" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          EAST LONDON, SOUTH AFRICA - 1996: Picketer holding Steve Biko's portrait during a demonstration in Oxford Street during The South African Truth and Reconciliation Commission (TRC) hearings in East London. (Photo by Gallo Images/Oryx Media Archive/Getty Images)
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
    </Card>
  </Grid>
</Grid>
<Grid container xs={{display:'flex', justifyContent:'flex-end'}}>
<Grid item xs>
    <Card 
      class=
      'card' sx={{ maxWidth: 300, boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography>
        <CardMedia
          component="img"
          height="210"
          image="https://live.staticflickr.com/7031/6507232963_e88cd0dfe9_b.jpg"
          alt="green iguana"
        />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
            Lizards are a widespread group of squamate reptiles, with over 6,000
            species, ranging across all continents except Antarctica
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
  </Grid>
  <Grid item xs>
    <Card 
      class=
      'card' sx={{ maxWidth: 300, boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography>
        <CardMedia
          component="img"
          height="210"
          image="https://live.staticflickr.com/7031/6507232963_e88cd0dfe9_b.jpg"
          alt="green iguana"
        />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
            Lizards are a widespread group of squamate reptiles, with over 6,000
            species, ranging across all continents except Antarctica
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
  </Grid>
  <Grid item xs>
  <Card 
      class=
      'card' sx={{ maxWidth: 300, boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography>
        <CardMedia
          component="img"
          height="220"
          image="https://live.staticflickr.com/7031/6507232963_e88cd0dfe9_b.jpg"
          alt="green iguana"
        />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
            Lizards are a widespread group of squamate reptiles, with over 6,000
            species, ranging across all continents except Antarctica
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
  </Grid>
</Grid>
  </Grid>
</Grid>
    <Grid container spacing={2} height="100vh">
  <Grid item xs={8}>
    <Item sx={{backgroundColor:"transparent", boxShadow:0,}}><p> lorem </p></Item>
  </Grid>
  <Grid item xs={4}>
    {/* <Item>xs=4</Item> */}
  </Grid>
  <Grid item xs={6} sx={{}}>
    <Item sx={{backgroundColor:"transparent",display:'flex', justifyContent:'flex-start', gap:4}}>
    <Card 
      class=
      'card' sx={{ maxWidth: 400,  boxShadow:0, border:0, bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      {/* <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography> */}
        <CardMedia
          component="img"
          height="250"
          image="https://caravans.library.northwestern.edu/img/works/26/26_640x.jpg"
          alt="green iguana"
        />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Mansa Musa. Detail from the Catalan Atlas showing the emperor of the Mali Empire, Musa I (c. 1280 - c. 1337 ) sitting on a throne and holding a gold coin; pen with coloured inks on parchment, 1375

          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
    <Card 
      class=
      'card' sx={{ maxWidth: 400,  boxShadow:0, border:0, bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      {/* <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography> */}
        <CardMedia
          component="img"
          height="250"
          image="https://idsb.tmgrup.com.tr/ly/uploads/images/2020/12/17/thumbs/871x871/79746.jpg"
          alt="green iguana"
        />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Nubian pyramids were built by the rulers of the ancient Kushite kingdoms. The area of the Nile valley known as Nubia, which lies in the north of present-day Sudan, was home to three Kushite kingdoms during antiquity. The first had its capital at Kerma between 2500 and 1500 B.C.
<br />
(AGF/UNIVERSAL IMAGES GROUP VIA GETTY IMAGES)

          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
    </Item>
  </Grid>
  <Grid item xs={6}>
    <Item sx={{backgroundColor:"transparent"}}> <p>lorem impsu</p></Item>
  </Grid>
</Grid>
<Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 3 }} sx={{height:"100vh"}}>
  <Grid item xs={12} sx={{backgroundImage:`url(https://artblart.files.wordpress.com/2013/04/036_twcpress_album-web.jpg)`, backgroundPosition:'center', backgroundRepeat:'none', backgroundSize:'contain', filter:'grayscale(1)'}}>
  </Grid>
  
</Grid>
<Grid container spacing={2} sx={{height:"100vh" }}>
  <Grid item xs={6} md={6} >
    <Item sx={{backgroundColor:'transparent', display:'flex', justifyContent:'center', alignItems:'center'}}>
    <Card 
      class=
      'card' sx={{ maxWidth: 600, height:"100%", boxShadow:0, border:0, padding:'2rem', bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      {/* <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography> */}
        <CardMedia
          component="img"
          height="100%"
          image="https://i.guim.co.uk/img/media/c246af51f8b11d556293d4616a134f6d55dda595/0_0_1390_2183/master/1390.jpg?width=1010&quality=45&auto=format&fit=max&dpr=2&s=8a33fbe703894560be3d2410c5f7d779"
          alt="green iguana"
        />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Nubian pyramids were built by the rulers of the ancient Kushite kingdoms. The area of the Nile valley known as Nubia, which lies in the north of present-day Sudan, was home to three Kushite kingdoms during antiquity. The first had its capital at Kerma between 2500 and 1500 B.C.
<br />
(AGF/UNIVERSAL IMAGES GROUP VIA GETTY IMAGES)

          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
   
    
    </Card>
    </Item>
  </Grid>
  <Grid item xs={6} md={6} sx={{backgroundColor:"transparent", boxShadow:0, display:'flex', justifyContent:'center', alignItems:'center', flexDirection:'column'}}>
    <Item sx={{backgroundColor:"transparent", boxShadow:0, display:'flex', justifyContent:'center', alignItems:'center', flexDirection:'column'}}> 
  <p>lorem </p>
<p>lorem</p>
  </Item>
  </Grid>
  

 

</Grid>
    </div>
</div>
  )
}
