

import * as React from 'react';
import { useEffect } from 'react'
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { styled } from '@mui/material/styles';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import {CardActionArea} from '@mui/material';
import Grid from '@mui/material/Grid';
import Paper from '@mui/material/Paper';
import "react-slideshow-image/dist/styles.css";
import Box from '@mui/material/Box';
import Stack from '@mui/material/Stack';
import { gsap } from "gsap/dist/gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

const theme = createTheme({
  typography: {
    h1:{
      fontSize:250,
      textTransform:"uppercase",
      textAlign:"center",
      fontFamily: 'Channe',
      letterSpacing:"0px",
      color:'#0C0A09',
      marginTop:"10rem",
      fontWeight:'200',
    },
    h2:{
      fontSize:60,
      textTransform:"uppercase",
      textAlign:"center",
      fontFamily: 'Channe',
      letterSpacing:"0px",
      color:'##0C0A09',
      marginTop:"10rem",
      fontWeight:'200',
    },
    subtitle1: {
      fontSize: 1,
    },
    body1: {
      fontWeight: 500,
    },
    button: {
      fontStyle: 'italic',
    },
    p:{
      fontFamily: 'Letter Gothic',
   width:"20%",
   textAlign:"left",
    },
    
  },
});

const Item = styled(Paper)(({ theme }) => ({
  backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
  ...theme.typography.body2,
  padding: theme.spacing(1),
  textAlign: 'center',
  color: theme.palette.text.secondary,
}));
const style = {
  imageContainer: {
      backgroundImage: "red",
  }
};
const posts = [
  {
  title:"fela kuti",
  exercpt: "How Fela changed afrobeats",
},
{
  title:"Mandela",
  exercpt: "How Mandela changed freedom",
},
{
  title:"Hugh Masekela",
  exercpt: "How Hugh changed Jazz",
},
]
export default function Home() {
  
  return (
<div className="wrapper">
<div className={styles.container}>
      <Head>
        <title >Maarifa blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      {}
      </div>
      <ThemeProvider theme={theme}>
        <Typography variant="h1">Maarifa</Typography>
      </ThemeProvider>
<div>
<img width="100%" height="100%" src="https://i.guim.co.uk/img/media/0e0714859d891913996c5c7c3b1241d4d616473b/0_0_2493_1661/master/2493.jpg?width=1920&quality=85&auto=format&fit=max&s=c548bb535ef1923f055311822a61176d" />
</div>

<Box m={8} 
        sx={{
          height: '100vh',
          width: "100%",
          display: 'inline-block',
          p: 1,
          mx: 1,
          bgcolor: (theme) =>
            theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',
          border: '1px solid',
          borderColor: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.800' : 'grey.300',
          borderRadius: 2,
          fontSize: '0.875rem',
          fontWeight: '700',
          textAlign: 'center',
          position: 'relative',
        }}
      >
        <Box
        sx={{
          width: '50%',
          p: 1,
          my: 1,
          bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',
          border: '1px solid',
          borderColor: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.800' : 'grey.300',
          borderRadius: 2,
          fontSize: '0.875rem',
          fontWeight: '700',
          textAlign: 'center',
          marginTop:"8rem",
        }}
      >
     <ThemeProvider theme={theme}>
        <Typography  variant="p" className="intro">Maarifa, the swahili word for "knowledge". The significance of that word lies within the purpose of this blog. This blog will serve as a digital space to connect with untold stories of a very faceted continent. Africa. Through publicly available media, Maarifa blog will showcase Africa from its muzzy pre-colonial incpetion, some of continent's most influential figures, the global cultural blueprints it has set, where the continent is today and where we can see Africa going and becoming {
          
        }.   </Typography>
        </ThemeProvider>
      </Box>
      <ThemeProvider theme={theme}>
        <Typography variant="h2">Recent Posts</Typography>
      </ThemeProvider>
      <div style={{ width: '100%', display:"flex", justifyContent:"flex-end",position:"absolute",  gap:0, bottom:8, right:0}}>
      <Card 
      class=
      'card' sx={{ maxWidth: 400, boxShadow:0, bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography>
          <img class="img"
      
       src="https://media.gettyimages.com/photos/le-musicien-nigrian-fela-anikulapo-kuti-paris-avant-sa-tourne-en-picture-id956729114?k=20&m=956729114&s=612x612&w=0&h=s8qFaqXXqpy6jQpegBZd2KjmtLba_26q8lY-p0_quw0=" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Le musicien nigérian Fela Anikulapo Kuti à Paris avant sa tournée américaine, en octobre 1986, France. (Photo by Patrick AVENTURIER/Gamma-Rapho via Getty Images)
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
         / Read more
        </Button>
      </CardActions>
    
    </Card>
    <Card  sx={{ maxWidth: 400,  boxShadow:0, bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800', }}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Golden Age of Mali Photography
          </Typography>
          <img class="img" 
       src="https://i.guim.co.uk/img/media/b1ddd6f579aa1c38f9fbdb34f9c0308da4236967/0_132_1989_1194/master/1989.jpg?width=1900&quality=45&auto=format&fit=max&dpr=2&s=f1c68ab432edd56b9c693e8fe2d3427a" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Malick Sidibé: the photographer who changed the idea of black beauty
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
        Read more
        </Button>
      </CardActions>
    </Card>
    <Card sx={{ maxWidth: 400,  boxShadow:0, bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800', }}>
      <CardActionArea>
                  <Typography gutterBottom variant="subtitle1" component="div">
     / Mother Africa - Timbuktu
          </Typography>
          <img class="img"
       src="https://i.guim.co.uk/img/media/b8aa1f03abbe1da0ff27e695db8c25dbaf3e630b/0_0_2830_1832/master/2830.jpg?width=1010&quality=45&auto=format&fit=max&dpr=2&s=faa563447076e3484e6b4ed85610287a" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          British colonial anthropologist Northcote Thomas took thousands of photographs and sound recordings of men, women and children in west Africa between 1909 and 1915
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
        Read more 
        </Button>
      </CardActions>
    </Card>
      </div >
      </Box>
      <Box sx={{ flexGrow: 1, height:"100%",  backgroundColor: '#dcd6c8',}}>
      <Grid container sx={{ flexGrow: 1, height:"100vh",  backgroundColor: '#dcd6c8',}}>
        <Grid item xs={6} style={style.paperContainer}  sx={{backgroundColor: '#dcd6c8', display:'flex', justifyContent:'center', alignItems:'center'}} >
        
          <Card sx={{ maxWidth: 350,  boxShadow:0, backgroundColor: '#dcd6c8' }}>
      <CardActionArea>
     
        <CardMedia
          component="img"
          height="350"
      image="https://autograph.org.uk/Content/Images/EditorImages/a%20-%20new%20structure%2Fonline%20image%20galleries%2F2021%2Foctober%2Fbarnor%2FBarnor-EY-stand.jpg"
          alt="green iguana"
        />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Yoga undergraduate Peter Dodoo, a student of Mr Strong #1, Ever Young studio, Accra, c. 1955
          <br />
          James Barnor 
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
     
    </Card>
        </Grid>
        <Grid item xs={6} sx={{backgroundImage:`url(https://i.guim.co.uk/img/media/4ea2d56aa4b5c9a04db58900318f4f1ce40c823c/0_0_3543_3582/master/3543.jpg?width=1010&quality=45&auto=format&fit=max&dpr=2&s=8dc5eb97fefac1b49200de4f192db7ac)`, backgroundPosition:'center', backgroundSize:"cover", paddingTop:"8rem"}}>
          {
          
        //   <Item> <CardMedia
        //   component="img"
   
        //   // image="https://i.guim.co.uk/img/media/4ea2d56aa4b5c9a04db58900318f4f1ce40c823c/0_0_3543_3582/master/3543.jpg?width=1010&quality=45&auto=format&fit=max&dpr=2&s=8dc5eb97fefac1b49200de4f192db7ac"
        //   alt="green iguana"
     
        // />
        // </Item>
        }
        </Grid>
      </Grid>
    </Box>

    <Grid container spacing={2} height="100vh" style={{position:"relative"}}>
  <Grid item xs={3}>
    <Item sx={{backgroundColor:"transparent", boxShadow:0,}}>
    <ThemeProvider theme={theme} sx={{display:"flex", justifyContent:"flex-start"}}>
        <Typography variant="h2">History</Typography>
      </ThemeProvider>
    </Item>
  </Grid>
  <Grid item xs={4}>
    {/* <Item>xs=4</Item> */}
  </Grid>
  <Grid item xs={6} sx={{position:""}}>
    <Item sx={{backgroundColor:"transparent", boxShadow:0, display:'flex', justifyContent:'flex-start', gap:4, position:"absolute", bottom:0,}} style={{position:"absolute", bottom:0, left:0,}}>
    <Card 
      class=
      'card' sx={{ maxWidth: 350,  boxShadow:0, border:0, bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      {/* <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography> */}
        <CardMedia
          component="img"
          height="220"
          image="https://caravans.library.northwestern.edu/img/works/26/26_640x.jpg"
          alt="green iguana"
        />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Mansa Musa. Detail from the Catalan Atlas showing the emperor of the Mali Empire, Musa I (c. 1280 - c. 1337 ) sitting on a throne and holding a gold coin; pen with coloured inks on parchment, 1375

          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary" style={{fontSize:"12px"}}>
          Read more
        </Button>
      </CardActions>
    
    </Card>
    <Card 
      class=
      'card' sx={{ maxWidth: 350,  boxShadow:0, border:0, bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      {/* <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography> */}
        <CardMedia
          component="img"
          height="220"
          image="https://idsb.tmgrup.com.tr/ly/uploads/images/2020/12/17/thumbs/871x871/79746.jpg"
          alt="green iguana"
        />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Nubian pyramids were built by the rulers of the ancient Kushite kingdoms. The area of the Nile valley known as Nubia, which lies in the north of present-day Sudan, was home to three Kushite kingdoms during antiquity. The first had its capital at Kerma between 2500 and 1500 B.C.
<br />
(AGF/UNIVERSAL IMAGES GROUP VIA GETTY IMAGES)

          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
    </Item>
  </Grid>
  <Grid item xs={6} style={{ fontFamily: 'Letter Gothic',}} style={{position:"", bottom:0, right:0, display:"flex", flexDirection:"column", justifyContent:"flex-end"}}>
  <Card style={{position:"absolute", top:"15%",right:0, height:"100%"}}
      class=
      'card' sx={{ maxWidth: 450, height:"100%", boxShadow:0, border:0, bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      {/* <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography> */}
        <CardMedia
          component="img"
          height="100%"
          image="https://www.worldhistory.org/uploads/images/10251.jpg?v=1612887304"
          alt="green iguana"
        />
              <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
       pyramids were built by the rulers of the ancient Kushite kingdoms. 
<br />
(AGF/UNIVERSAL IMAGES GROUP VIA GETTY IMAGES)

          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
   
    
    </Card>
    <Item sx={{backgroundColor:"transparent", fontFamily: 'Letter Gothic', boxShadow:0, textAlign:"left"}}> <p>The West is fixated on slavery, but Africa's history is far more complex than that of European colonization.</p>
    <p>The first important African civilization, however, was Ancient Egypt. Egypt began producing crops around 4000 BCE. These peoples evolved into early Egyptian states 500 years later, and in 3200 BCE they became the great Egyptian civilization. Despite Egypt's early success, sub-Saharan African empires did not form and survive for lengthy periods of time until until 700 CE. </p>
    <p>Africa's greatest empires eventually fell apart due to a lack of culture and a technological advantage, and were frequently replaced by another.</p>
    <p>Mali ascended to the throne of Ghana, and the Songhai followed suit. Typically, each empire expanded upon the social, political, commercial, and military organization created by their ancestors, albeit in a variety of ways and over different portions of West Africa. States and civilizations arose and prospered across the continent by 1000 CE. As these civilizations evolved to meet local environmental, political, and social needs, their structures changed.</p>
    </Item>
    
  </Grid>
</Grid>
<Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 3 }} style={{height:"100vh", display:"flex", justifyContent:"center", alignItems:"center"}}>
  <Grid item xs={6}>
    <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 3 }}>
  <Grid item xs={6}>
  <Card 
      class=
      'card' sx={{ maxWidth: 550, boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / How the West Destroyed African Civilization through Colonialism
          </Typography>
          <img class="img"
       src="https://d1sxy7l4fhu207.cloudfront.net/assets/img/collectionbannerthumbnails/9781851173303.jpg" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Marcus Garvey "Africa's Provisional President" during the renaming of the ship from the "General G.W. Goethals" to the S.S Booker T. Washington. (Photo By: /NY Daily News via Getty Images)
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
  </Grid>
  <Grid item xs={6}>
  <Card 
      class=
      'card' sx={{ maxWidth: 500, boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography>
          <img class="img"
       src="https://upload.wikimedia.org/wikipedia/commons/c/cd/Ota_Benga_at_1904_World%27s_Fair.jpg" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Marcus Garvey "Africa's Provisional President" during the renaming of the ship from the "General G.W. Goethals" to the S.S Booker T. Washington. (Photo By: /NY Daily News via Getty Images)
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
  </Grid>
  <Grid item xs={6}>
  <Card 
      class=
      'card' sx={{ maxWidth: 500, boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Confronting the colonial archive
          </Typography>
          <img class="img"
       src="https://i.guim.co.uk/img/media/7e4d8fbb770fc8fa0044b8b8fd5ccc0bbbe1382f/0_8_2835_1838/master/2835.jpg?width=1010&quality=45&auto=format&fit=max&dpr=2&s=82a09a98f7b5454bb1fd5d849848cf32" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Marcus Garvey "Africa's Provisional President" during the renaming of the ship from the "General G.W. Goethals" to the S.S Booker T. Washington. (Photo By: /NY Daily News via Getty Images)
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
  </Grid>
  <Grid item xs={6}>
  <Card 
      class=
      'card' sx={{ maxWidth: 500, boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
/ Ota Benga's Tragic Life As The Bronx Zoo's Human Exhibit
          </Typography>
          <img class="img"
       src="https://c.files.bbci.co.uk/1D6B/production/_114113570_otabenga976.png" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Marcus Garvey "Africa's Provisional President" during the renaming of the ship from the "General G.W. Goethals" to the S.S Booker T. Washington. (Photo By: /NY Daily News via Getty Images)
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
  </Grid>
</Grid>
  </Grid>
  <Grid item xs={6}>
  <ThemeProvider theme={theme} sx={{display:"flex", justifyContent:"flex-start"}}>
        <Typography variant="h2">Colonisation</Typography>
      </ThemeProvider>

  </Grid>
</Grid>

  <Grid item xs={6} md={8} style={{position:"relative"}}>
    <Item style={{height:"100vh",backgroundColor:"#070606", color:"#dcd6c8", display:"flex", justifyContent:"center", alignItems:"column", flexDirection:"column"}}>

        <Typography variant="h2" style={{fontSize:'25rem'}}>400 years</Typography>
        <Stack
  direction="row"
  justifyContent="space-around"
  alignItems="center"
  spacing={2}
  style={{position:"absolute", top:"50%", left:"50%", transform:"translate(-50%, -50%)", width:"100%"}}
>
<Item xs={{backgroundColor:"transparent"}} style={{backgroundColor:"transparent"}}>
  <Card sx={{ maxWidth: 500, backgroundColor:"transparent" }}>
      <CardActionArea>
        <CardMedia
        style={{width:"350px",height:"300px", objectFit:"cover", objectPosition:'top'}}
          component="img"
          height="300"
          image="https://assets.catawiki.nl/assets/2017/11/14/c/9/9/c99fe073-1048-405b-b330-dbd02c871bda.jpg"
          alt="green iguana"
        />
        
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Share
        </Button>
      </CardActions>
    </Card>
</Item>
<Item xs={{backgroundColor:"transparent"}} style={{backgroundColor:"transparent"}}>
  <Card sx={{ maxWidth: 500, backgroundColor:"transparent" }}>
      <CardActionArea>
      <CardMedia
        style={{width:"300px",height:"280px", objectFit:"cover", objectPosition:"center top"}}
          component="img"
          height="300"
          image="https://i0.wp.com/hadithi.africa/wp-content/uploads/2019/09/97160783.jpg?resize=670%2C1024&ssl=1"
          alt="green iguana"
        />
        
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Share
        </Button>
      </CardActions>
    </Card>
  </Item>
  <Item xs={{backgroundColor:"transparent"}} style={{backgroundColor:"transparent"}}>
  <Card sx={{ maxWidth: 500, backgroundColor:"transparent" }}>
      <CardActionArea>
      <CardMedia
        style={{width:"300px",height:"280px", objectFit:"cover"}}
          component="img"
          height="300"
          image="https://d7nm3c5ruslmy.cloudfront.net/africanexponent-com-client/images/99e140d4-6082-4f5e-bcb2-6c15be40ad1d-the-west_aspR_1.783_w943_h529_e400.png"
          alt="green iguana"
        />
        
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Share
        </Button>
      </CardActions>
    </Card>
  </Item>
  <Item xs={{backgroundColor:"transparent"}} style={{backgroundColor:"transparent"}}>
  <Card sx={{ maxWidth: 500, backgroundColor:"transparent" }}>
      <CardActionArea>
      <CardMedia
        style={{width:"300px",height:"280px", objectFit:"cover"}}
          component="img"
          height="300"
          image="https://miro.medium.com/max/1400/1*b2XwWEB6vqCnpk7WDzzAKQ.png"
          alt="green iguana"
        />
        
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Share
        </Button>
      </CardActions>
    </Card>
  </Item>
  <Item xs={{backgroundColor:"transparent"}} style={{backgroundColor:"transparent"}}>
  <Card sx={{ maxWidth: 500, backgroundColor:"transparent" }}>
      <CardActionArea>
      <CardMedia
        style={{width:"300px",height:"300px", objectFit:"cover"}}
          component="img"
          height="300"
          image="https://www.groundup.org.za/media/uploads/images/Third%20Party/1976-20160616-JuhanKuus.jpg"
          alt="green iguana"
        />
        
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Share
        </Button>
      </CardActions>
    </Card>
  </Item>
  <Item xs={{backgroundColor:"transparent"}} style={{backgroundColor:"transparent"}}>
  <Card sx={{ maxWidth: 500, backgroundColor:"transparent" }}>
      <CardActionArea>
      <CardMedia
        style={{width:"300px",height:"300px", objectFit:"cover", objectPosition:"top"}}
          component="img"
          height="300"
          image="https://www.theafricancourier.de/wp-content/uploads/2020/06/King-Leopolds-Crime-1-rotated.jpg"
          alt="green iguana"
        />
        
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Share
        </Button>
      </CardActions>
    </Card>
  </Item>
  
  
</Stack>
    </Item>
  </Grid>


    <Grid container  xs={{height:"100vh", backgroundColor:"red"}} style={{height:"100vh", display:"flex", alignItems:"center", justifyContent:"center"}}>
  <Grid item xs={6} md={4}>
    <Item sx={{backgroundColor:"transparent", boxShadow:0,}}>
    <ThemeProvider theme={theme}>
        <Typography variant="h2">Political</Typography>
      </ThemeProvider>
    </Item>
  </Grid>
  <Grid item xs={6} md={8} sx={{marginTop:"0rem"}}>
  
  <Grid container spacing={0}>
  <Grid item xs >
  <Card 
      class=
      'card' sx={{ maxWidth: 400, boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography>
          <img class="img"
       src="https://media.gettyimages.com/photos/marcus-garvey-africas-provisional-president-during-the-renaming-of-picture-id466721774?k=20&m=466721774&s=612x612&w=0&h=4LT4fukoZ1bCGbateWt5TUegBTG1riffzIJNXCvfVlI=" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Marcus Garvey "Africa's Provisional President" during the renaming of the ship from the "General G.W. Goethals" to the S.S Booker T. Washington. (Photo By: /NY Daily News via Getty Images)
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>

  </Grid>
  <Grid item xs >
  <Card 
      class=
      'card' sx={{ maxWidth: "100%", boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography>
       <img class="img"
       src="https://lh3.googleusercontent.com/RkyTiCFq4ZUQE2S30s8I9LAgS1EkXqqr9QlmjSy6NXOKBiw1bfqAeRLPWmf-hSCmUOpuBjf5AfhBNkkyjSfr" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          196: Picketer holding Steve Biko's portrait during a demonstration in Oxford Street during The South African Truth and Reconciliation Commission (TRC) hearings in East London. (Photo by Gallo Images/Oryx Media Archive/Getty Images)
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
  
    </Card>
  </Grid>
  <Grid item xs={4}>

  <Card 
      class=
      'card' sx={{ maxWidth: 400, boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
  / The love story that shocked the world
          </Typography>
        <img class="img"
       src="https://live.staticflickr.com/7031/6507232963_e88cd0dfe9_b.jpg" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
            Lizards are a widespread group of squamate reptiles, with over 6,000
            species, ranging across all continents except Antarctica
            <br />
            BBC News
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
  </Grid>
</Grid>

<Grid container xs={{display:'flex', justifyContent:'flex-end', marginTop:"8rem"}}>
<Grid item xs={4}>
    <Card 
      class=
      'card' sx={{ maxWidth: 400, boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography>
          <img class="img"
       src="https://media.gettyimages.com/photos/president-of-ghana-kwame-nkrumah-with-his-wife-fathia-nkrumah-circa-picture-id114953929?k=20&m=114953929&s=612x612&w=0&h=8wioOHJhWHP7iLawXDCp5hmKZ67zH2weSCtOgqwUpMg=" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          President of Ghana Kwame Nkrumah (1909 - 1972) with his wife Fathia Nkrumah (nee Rizk, 1932 - 2007), circa 1963. (Photo by Popperfoto via Getty Images/Getty Images)
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
  </Grid>
  <Grid item xs>
    <Card 
      class=
      'card' sx={{ maxWidth: 400, boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography>
          <img class="img"
       src="https://media.gettyimages.com/photos/south-african-antiapartheid-activist-robert-sobukwe-reads-a-newspaper-picture-id514683104?k=20&m=514683104&s=612x612&w=0&h=2cAPsQ97XhMrQ3c1hMVi0z-X-mEF-q99Dhv36Hz172k=" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          South African anti-Apartheid activist Robert Sobukwe reads a newspaper and smokes in his cell at the prison on Robben Island. He was the leader of the Pan-Africanist Congress, a radical offshoot of the African National Congress. Sobukwe was imprisoned from 1960, until his death in 1978.
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
  </Grid>
  <Grid item xs>
  <Card 
      class=
      'card' sx={{ maxWidth: 400, boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography>
          <img class="img"
       src="https://media.gettyimages.com/photos/captain-thomas-sankara-leader-of-burkina-faso-picture-id72368152?k=20&m=72368152&s=612x612&w=0&h=Bq_363-wFOPvsmmIR6o355Ri0q1GVfxUKHajjMZZfmc=" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          BURKINA FASO - FEBRUARY 01: Captain Thomas Sankara, leader of Burkina Faso. (Photo by William F. Campbell/Getty Images)
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
  </Grid>
</Grid>
  </Grid>
</Grid>
<Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 3 }} sx={{height:"100vh",color:"#dcd6c8"}}>

<section className="artist section">
<ThemeProvider theme={theme}>
        <Typography variant="h2">Died in detention</Typography>
      </ThemeProvider>
      <p style={{color:"#dcd6c8"}}>One of the many weapons employed by the government to quash dissent was detaining and imprisoning anyone who opposed the Apartheid regime. Detention became more widely employed as a legal weapon that could silence an individual, a group, or even an entire society. Deaths in custody, particularly during interrogation, became more common as a result. There were 67 deaths between Solwandle Looksmart Ngudle's death on September 3, 1963, and Alfred Mabake Makaleng's death on August 26, 1988.</p>
  <span class="left-scroll">
    <ul>
<li>Ngudle Solwandle</li>
<li>Mampe Bellington</li>
<li>Gaga Ngeni</li>
<li>Biko Steve</li>
<li>Shonyeka Hangula</li>
<li>Madiba Alpheus</li>
<li>Lenkoe James&iacute;</li>
<li>Monakgotla Jacob</li>
<li>Mayekiso Caleb</li>
</ul>
  </span>
    <span class="right-scroll">
    <ul>
<li>Cuthsela Mthayeni</li>
<li>Tshwane William</li>
<li>Mohapi Mapetla</li>
<li>Mazwembe Luke</li>
<li>Mbatha Dumisani</li>
<li>Mashabane Jacob</li>
<li>Mzolo Edward&iacute;</li>
<li>Mamashila Ernest</li>
<li>shazibane Wellington</li>
</ul>
  </span>
   <span class="left-scroll">
    <ul>
<li>Mabelane Mathews</li>
<li>Malinga Samuel</li>
<li>Khoza Aaron</li>
<li>Mamashila Ernest</li>
<li>Malaza Sipho</li>
<li> Tabalaza Lungile</li>
<li>Ndzumo Saull&iacute;</li>
<li> Mgqweto Manana</li>
<li>Muofhe Tshifhiwa</li>
</ul>
        
  </span>
   <span class="right-scroll">
    <ul>
<li>Mndawe Simon</li>
<li>Tshikudo, Samuel</li>
<li>Sipele, Mxolisi</li>
<li>Mthethwa Ephraim</li>
<li>Raditsela Andries</li>
<li>Ndondo Batandwa</li>
<li>Kutumela Makompe&iacute;</li>
<li>Nchabaleng Peter</li>
<li>Jacobs Xoliso</li>
</ul>
  </span>
   <span class="left-scroll">
    <ul>
<li>Marule Simon</li>
<li>Bani Nobandla</li>
<li> Zokwe Sithembele</li>
<li>Sithole Clayton Sizwe</li>
<li>Tlhotlhomisang Lucas</li>
<li>Madisha Donald Thabela</li>
<li>Shivute Michae&iacute;</li>
<li>Peter Paul Rubens</li>
<li>Michelangelo</li>
</ul>
  </span>
   <span class="right-scroll">
   <ul>
<li>Ngudle Solwandle</li>
<li>Mampe Bellington</li>
<li>Gaga Ngeni</li>
<li>Biko Steve</li>
<li>Shonyeka Hangula</li>
<li>Madiba Alpheus</li>
<li>Lenkoe James&iacute;</li>
<li>Monakgotla Jacob</li>
<li>Mayekiso Caleb</li>
</ul>
  </span>
   
</section>
  {/* </Grid>
<Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 3 }} sx={{height:"100vh"}}>
  <Grid item xs={12} sx={{backgroundImage:`url(https://artlogic-res.cloudinary.com/w_750,c_limit,f_auto,fl_lossy,q_auto/ws-artlogicwebsite0082/usr/images/artworks/main_image/items/45/45d2736d80b043c59eb86dcb49d8891a/nubukebm009.jpg)`, backgroundPosition:'center', backgroundRepeat:'repeat', backgroundSize:'contain', filter:'grayscale(1)'}}>
  </Grid> */}
</Grid>
<Grid container spacing={0} height="100vh">
  <Grid item xs={6} md={4} sx={{backgroundImage:`url(https://i.guim.co.uk/img/media/b345bf6bae49d0a367c093e996ad67343d9fbd17/0_20_7054_7056/master/7054.jpg?width=1010&quality=45&auto=format&fit=max&dpr=2&s=3f713cbc244137f63e55bb6fa7cbc979)`, backgroundPosition:'center', backgroundRepeat:'no-repeat', backgroundSize:'cover', filter:'grayscale(1)'}}>
 
  </Grid>
  <Grid item xs={6} md={4} sx={{backgroundImage:`url(https://i.guim.co.uk/img/media/f54c2918b0f32238902c8dad852e10f38855d43e/0_40_7037_7033/master/7037.jpg?width=1010&quality=45&auto=format&fit=max&dpr=2&s=b0087f279161b8641a3cf14a25e02203)`, backgroundPosition:'center', backgroundRepeat:'no-repeat', backgroundSize:'cover', filter:'grayscale(1)'}}>

  </Grid>
  <Grid item xs={6} md={4} sx={{backgroundImage:`url(https://i.guim.co.uk/img/media/4098b9d3f8d78155bde5f47efc1cb89755455818/39_0_6981_6983/master/6981.jpg?width=1010&quality=45&auto=format&fit=max&dpr=2&s=cbc386a65e92575e3c2151f93cc8fd2b)`, backgroundPosition:'center', backgroundRepeat:'no-repeat', backgroundSize:'cover', filter:'grayscale(1)'}}>


  </Grid>
</Grid>

<Grid container spacing={0} sx={{height:"100%" }}>
  <Grid item xs={6} md={6} >
    <Item sx={{backgroundColor:'transparent', boxShadow:0, display:'flex', justifyContent:'center', alignItems:'center'}}>
    <Card 
      class=
      'card' sx={{ maxWidth: 600, height:"100%", boxShadow:0, border:0, padding:'2rem', bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      {/* <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography> */}
        <CardMedia
          component="img"
          height="100%"
          image="https://i.guim.co.uk/img/media/c246af51f8b11d556293d4616a134f6d55dda595/0_0_1390_2183/master/1390.jpg?width=1010&quality=45&auto=format&fit=max&dpr=2&s=8a33fbe703894560be3d2410c5f7d779"
          alt="green iguana"
        />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Nubian pyramids were built by the rulers of the ancient Kushite kingdoms. The area of the Nile valley known as Nubia, which lies in the north of present-day Sudan, was home to three Kushite kingdoms during antiquity. The first had its capital at Kerma between 2500 and 1500 B.C.
<br />
(AGF/UNIVERSAL IMAGES GROUP VIA GETTY IMAGES)

          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
   
    
    </Card>
    </Item>
  </Grid>

  <Grid item xs={6} md={6} sx={{backgroundColor:"transparent", position:"relative", boxShadow:0, display:'flex', flexDirection:'column'}}>
    <Item sx={{backgroundColor:"transparent", boxShadow:0}}> <ThemeProvider theme={theme} sx={{display:"flex", justifyContent:"flex-end", backgroundColor:"transparent"}}>
        <Typography variant="h2" xs={{textAlign:"right"}}>Fashion</Typography>
      </ThemeProvider></Item>
    <Item sx={{backgroundColor:"transparent", boxShadow:0, display:'flex', justifyContent:'center', alignItems:'center', flexDirection:'column'}}> 
  <p>lorem </p>
<p>lorem</p>
  </Item>
  <Stack
  direction="row"

  spacing={2}
>
  <Item><Card 
      class=
      'card' sx={{maxWidth: 400, boxShadow:0, bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography>
          <img class="img-fashion" style={{height:"100%"}}
       src="https://i.guim.co.uk/img/media/4c0d9dcfb8090d564b33107665d438ffa7ff84bd/0_0_1208_1697/master/1208.jpg?width=1010&quality=85&auto=format&fit=max&s=36937e5bfcf27365a25fa2ed46a8b557" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          BURKINA FASO - FEBRUARY 01: Captain Thomas Sankara, leader of Burkina Faso. (Photo by William F. Campbell/Getty Images)
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card></Item>
  <Item>

  <Card 
      class=
      'card' sx={{maxWidth: 400, boxShadow:0, bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography>
          <img class="img-fashion" style={{height:"100%"}}
       src="https://artblart.files.wordpress.com/2013/04/033_twcpress_williams-web.jpg" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          BURKINA FASO - FEBRUARY 01: Captain Thomas Sankara, leader of Burkina Faso. (Photo by William F. Campbell/Getty Images)
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
  </Item>

</Stack>
  </Grid>
</Grid>
<div  style={ {height:"100vh", display:"flex", justifyContent:"center", alignItems:"center", position:"relative"}}>
<ThemeProvider theme={theme}>
        <Typography variant="2"  style={{position:"absolute", top:0, left:0, fontSize:"8rem"}}>Entertainment</Typography>
        <Typography style={{position:"absolute", top:10, left:0,}}>lorem o n m</Typography>
      </ThemeProvider>
<Stack
  direction={{ xs: 'column', sm: 'row' }}
  spacing={{ xs: 1, sm: 2, md: 5 }}
  justifyContent="center"
  alignItems="center">
  <Item>
  <Card  sx={{ maxWidth: 400, boxShadow:0, bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800', }}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Golden Age of Mali Photography
          </Typography>
          <img class="img" 
          height="499px"
       src="https://media.gettyimages.com/photos/jazz-trumpeter-hugh-masekela-performs-onstage-in-1968-picture-id74313491?k=20&m=74313491&s=612x612&w=0&h=MR-bbFsOk6hmmQhz8FajotjhTHH1lx5LyDWeXaKQMU4=" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          1968: Jazz trumpeter Hugh Masekela performs onstage in 1968. (Photo by Tom Copi/Michael Ochs Archives/Getty Images )
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
        Read more
        </Button>
      </CardActions>
    </Card>
  </Item>
  <Item>

  <Card  sx={{ maxWidth: 400, boxShadow:0, bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800', }}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Golden Age of Mali Photography
          </Typography>
          <img class="img" 
          height="499px"
       src="https://i.guim.co.uk/img/media/99eca4dd89d4603dcfff5cda1a75b5d3598a0eb3/0_0_3673_5112/master/3673.jpg?width=1010&quality=45&auto=format&fit=max&dpr=2&s=d4f56a8ed971d7837ef9afe9c7c11ed4" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Sembène coined the phrase ‘megotage’, a spoof on the word ‘montage’, to describe African film-making. A megot was the butt of a cigarette, which enterprising young men would collect, gathering the scraps of tobacco to make one whole new smoke. In impoverished Senegal, Sembène used his resourcefulness to find ways to get his films made. He’d use the leftover scraps of films that his friends in Paris would save, and borrowed money from friends and used his relatives as crew
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
        Read more
        </Button>
      </CardActions>
    </Card>
  </Item>
  <Item>
  <Card 
      class=
      'card' sx={{ maxWidth: 400, boxShadow:0, bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Mama Africa - Miriam Makeba
          </Typography>
          <img class="img"
       src="https://lh3.googleusercontent.com/nVk1SnfjdS-ce1rs30QaBWJV5GybyQ2_qi7-iTL8GGY1kdfDcNPFi9IxdbsaCevx_NmKk-mnfKi7IoKH25U2-hc=s1500-pp" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Le musicien nigérian Fela Anikulapo Kuti à Paris avant sa tournée américaine, en octobre 1986, France. (Photo by Patrick AVENTURIER/Gamma-Rapho via Getty Images)
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
         / Read more
        </Button>
      </CardActions>
    
    </Card>
  </Item>
  <Item>
  <Card 
      class=
      'card' sx={{ maxWidth: 400, boxShadow:0, bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Father of Desert Blues - Ali Farka Toure
          </Typography>
          <img class="img"
       src="https://media.gettyimages.com/photos/photo-of-ali-farka-toure-picture-id86116925?k=20&m=86116925&s=612x612&w=0&h=-7Ly4NN-1J284eLFc4OwE_O1rRZaaCuUR6RK-NRDbTE=" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Le musicien nigérian Fela Anikulapo Kuti à Paris avant sa tournée américaine, en octobre 1986, France. (Photo by Patrick AVENTURIER/Gamma-Rapho via Getty Images)
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
         / Read more
        </Button>
      </CardActions>
    
    </Card>
  </Item>
</Stack>
    </div>
    <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 3 }} style={{height:"100vh", display:"flex", justifyContent:"center", alignItems:"center"}}>
  <Grid item xs={6}>
    <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 3 }}>
  <Grid item xs={6}>
  <Card 
      class=
      'card' sx={{ maxWidth: 550, boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / How the West Destroyed African Civilization through Colonialism
          </Typography>
          <img class="img"
       src="https://d1sxy7l4fhu207.cloudfront.net/assets/img/collectionbannerthumbnails/9781851173303.jpg" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Marcus Garvey "Africa's Provisional President" during the renaming of the ship from the "General G.W. Goethals" to the S.S Booker T. Washington. (Photo By: /NY Daily News via Getty Images)
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
  </Grid>
  <Grid item xs={6}>
  <Card 
      class=
      'card' sx={{ maxWidth: 500, boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Fela Kuti: The Father of Afrobeats
          </Typography>
          <img class="img"
       src="https://upload.wikimedia.org/wikipedia/commons/c/cd/Ota_Benga_at_1904_World%27s_Fair.jpg" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Marcus Garvey "Africa's Provisional President" during the renaming of the ship from the "General G.W. Goethals" to the S.S Booker T. Washington. (Photo By: /NY Daily News via Getty Images)
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
  </Grid>
  <Grid item xs={6}>
  <Card 
      class=
      'card' sx={{ maxWidth: 500, boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
         / Confronting the colonial archive
          </Typography>
          <img class="img"
       src="https://i.guim.co.uk/img/media/7e4d8fbb770fc8fa0044b8b8fd5ccc0bbbe1382f/0_8_2835_1838/master/2835.jpg?width=1010&quality=45&auto=format&fit=max&dpr=2&s=82a09a98f7b5454bb1fd5d849848cf32" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Marcus Garvey "Africa's Provisional President" during the renaming of the ship from the "General G.W. Goethals" to the S.S Booker T. Washington. (Photo By: /NY Daily News via Getty Images)
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
  </Grid>
  <Grid item xs={6}>
  <Card 
      class=
      'card' sx={{ maxWidth: 500, boxShadow:0,  bgcolor: (theme) =>
          theme.palette.mode === 'dark' ? '#101010' : 'transparent',
          color: (theme) =>
            theme.palette.mode === 'dark' ? 'grey.300' : 'grey.800',}}>
      <CardActionArea>
      <Typography gutterBottom variant="subtitle1" component="div">
/ Ota Benga's Tragic Life As The Bronx Zoo's Human Exhibit
          </Typography>
          <img class="img"
       src="https://c.files.bbci.co.uk/1D6B/production/_114113570_otabenga976.png" />
        <CardContent>
          <ThemeProvider theme={theme}>
          <Typography variant="p" color="text.secondary">
          Marcus Garvey "Africa's Provisional President" during the renaming of the ship from the "General G.W. Goethals" to the S.S Booker T. Washington. (Photo By: /NY Daily News via Getty Images)
          </Typography>
          </ThemeProvider>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button size="small" color="primary">
          Read more
        </Button>
      </CardActions>
    
    </Card>
  </Grid>
</Grid>
  </Grid>
  <Grid item xs={6}>
  <ThemeProvider theme={theme} sx={{display:"flex", justifyContent:"flex-start"}}>
        <Typography variant="h2">Current affairs</Typography>
      </ThemeProvider>

  </Grid>
</Grid>
    </div>
</div>
  )
}
